[package]
name = "osom_lib_try_clone"
version = "0.1.30"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
description = "TryClone trait and base implementations for osom_lib."
documentation = "https://docs.rs/osom_lib_strings"

[dependencies]
priv_osom_lib_try_clone_proc_macros = { path = "../priv_osom_lib_try_clone_proc_macros", version = "0.1" }

[dev-dependencies]
rstest = { workspace = true }

[features]
default = []
