[package]
name = "osom_lib_arc"
version = "0.1.31"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
description = "ABI-stable atomic reference counted pointers for osom_lib."
documentation = "https://docs.rs/osom_lib_arc"

[dependencies]
osom_lib_alloc = { path = "../osom_lib_alloc", version = "0.1" }
osom_lib_primitives = { path = "../osom_lib_primitives", version = "0.1" }
osom_lib_reprc = { path = "../osom_lib_reprc", version = "0.1" }
osom_lib_try_clone = { path = "../osom_lib_try_clone", version = "0.1" }
osom_lib_macros = { path = "../osom_lib_macros", version = "0.1" }

[dev-dependencies]
rstest = { workspace = true }

[features]
default = []
std = ["osom_lib_alloc/std"]
