[package]
name = "osom_lib_primitives"
version = "0.1.33"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
description = "Core ABI-stable primitive types used across osom_lib crates."
documentation = "https://docs.rs/osom_lib_primitives"

[dependencies]
paste = { workspace = true }
serde = { workspace = true, optional = true }

osom_lib_try_clone = { path = "../osom_lib_try_clone", version = "0.1" }
osom_lib_reprc = { path = "../osom_lib_reprc", version = "0.1" }

[dev-dependencies]
rstest = { workspace = true }
osom_lib_test_helpers = { path = "../osom_lib_test_helpers", version = "0.1" }

[features]
default = []
serde = ["dep:serde"]