[package]
name = "osom_lib_alloc"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
osom_lib_reprc = { path = "../osom_lib_reprc", version = "0.1" }
libc = { workspace = true, optional = true }

[features]
default = ["std"]
std = ["libc"]
