[package]
name = "osom_lib_test_helpers"
version = "0.1.33"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
description = "Test helpers for osom_lib (and not only) crates."

[lib]

[dependencies]
serde = { workspace = true, features=["std"] }
serde_json = { workspace = true }

[features]
default = []
