[package]
name = "priv_osom_lib_tests"
version = "0.1.21"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
description = "Internal crate containing test helpers."

[lib]

[dependencies]
serde = { workspace = true, features=["std"] }
serde_json = { workspace = true }

[features]
default = []
