[package]
name = "osom_lib_entropy_cprng"
version = "0.1.30"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
description = "Cryptographically secure PRNG seeded from OS entropy for osom_lib."
documentation = "https://docs.rs/osom_lib_entropy_cprng"

[dependencies]
osom_lib_reprc = { path = "../osom_lib_reprc", version = "0.1" }
osom_lib_entropy = { path = "../osom_lib_entropy", version = "0.1" }
osom_lib_prng = { path = "../osom_lib_prng", version = "0.1" }
osom_lib_try_clone = { path = "../osom_lib_try_clone", version = "0.1" }
