[package]
name = "osom_lib_proc_macro_helpers_level2"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license-file.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
